#  Feishu 飞书
APP_ID: cli_xxx
APP_SECRET: xxx
APP_ENCRYPT_KEY: xxx
APP_VERIFICATION_TOKEN: xxx

# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: SDBot

# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001

# Stable Diffusion WebU的地址，启动参数中要加入--api
WEBUI_HOST: IP or Domain
WEBUI_PORT: 7860
WEBUI_USE_HTTPS: false
# 如果参数启用了API认证"--api-auth user:pwd"，需要填写用户名和密码
WEBUI_USER:
WEBUI_PASSWORD:

# 阿里云翻译服务，每个月有一百万字符的免费额度，完全够用了，需要自行申请：https://mt.console.aliyun.com/
ALIYUN_ACCESS_KEY_ID: 1234abcd
ALIYUN_ACCESS_KEY_SECRET: 1234abcd
# 根据你开通的服务区域填写，比如（杭州）：cn-hangzhou
ALIYUN_MT_REGION_ID: cn-hangzhou