#  Feishu 飞书
APP_ID: cli_xxx
APP_SECRET: xxx
APP_ENCRYPT_KEY: xxx
APP_VERIFICATION_TOKEN: xxx

# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: SDBot

# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001

# Stable Diffusion WebU的地址，启动参数中要加入--api
WEBUI_URL: https://xxx/
WEBUI_USER: user
WEBUI_PASSWORD: password